---
title: "Luftwaffe Airfields 1935-45 (France with Corsica and Channel Islands)"
author: "Alessandro Speranza"
date: "11/6/2021"
output:
  html_document:
    keep_md: yes
    number_sections: yes
    toc: yes
    toc_float:
      collapsed: no
---

#text_mining
#tidyverse
#pdf_data

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cash = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(pdftools)
library(funModeling)
library(here)
```

Data Source: [http://ww2.dk/Airfields%20-%20France.pdf]

# Get the pdf document
```{r get_pdf_doc}

here_data <- here("PDF_DAT - Luftwaffe Airfields 1935-45 (France with Corsica and Channel Islands)/data") 

# Download from the web the pdf document
utils::download.file("http://ww2.dk/Airfields%20-%20France.pdf", here("PDF_DAT - Luftwaffe Airfields 1935-45 (France with Corsica and Channel Islands)", "data", "Airfields - France.pdf"), mode = "wb")

# Create the vector pdf which contains all the pdf pages
pdf <- pdftools::pdf_text(here("PDF_DAT - Luftwaffe Airfields 1935-45 (France with Corsica and Channel Islands)", "data", "Airfields - France.pdf"))

# See the text of page 5
base::cat(pdf[5]) #cat function concatenates and prints. it's more useful than the simple pdf[5] 


# Retrieve pdf info about the author, version, etc
info <- pdf_info(here("PDF_DAT - Luftwaffe Airfields 1935-45 (France with Corsica and Channel Islands)", "data", "Airfields - France.pdf"))
```

Proceed with tutorial [https://r-posts.com/how-to-extract-data-from-a-pdf-file-with-r/]
